---
- name: Pull image for docker-gen nginx proxy
  command: docker pull "{{ docker_gen_image }}"

- name: Deploy docker-gen nginx proxy
  docker:
    name: "{{ docker_gen_container_name }}"
    image: "{{ docker_gen_image }}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d 
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /opt/nginx/certs:/etc/nginx/certs:ro
      - /path/to/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock
    state: started
  
