---
- name: Launch Ghost application container
  docker_container:
    name: ghost
    image: "{{ ghost_image }}"
    restart_policy: always
    volumes_from: ghost-data
    env:
      GHOST_URL: "{{ domain_name }}"
      NODE_ENV: production
      VIRTUAL_HOST: "{{ domain_name }}"
      VIRTUAL_PORT: "{{ ghost_port }}"
      LETSENCRYPT_HOST: "{{ domain_name }}"
      LETSENCRYPT_EMAIL:  "{{ letsencrypt_email }}"
    networks:
      - name: "{{ docker_network_name }}"
    expose:
      - "{{ ghost_port }}:{{ ghost_port }}"
