---
- name: Download docker image Ghost backup
  docker_image:
    name: "{{ ghost_backup_image }}"

- name: Launch backup container
  docker_container:
    name: ghost-backup
    image: "{{ ghost_backup_image }}"
    volumes:
      - /backup
    volumes_from:
      - ghost-data
    restart_policy: always
    state: started
    networks:
      - name: ghost
