---
- name: Pull image for Ghost
  docker_image:
    name: "{{ ghost_image }}"

- name: Include configuration task file
  include: configuration.yml

- name: Include data volume task file
  include: data.yml

- name: Include application task file
  include: application.yml

- name: Include backup task file
  include: backup.yml

