---
- name: Install python setup tools
  yum:
    name: python-setuptools

- name: Install Pypi
  easy_install: 
    name: pip

- name: Install docker-py
  pip:
    name: docker-py

- name: Install Docker
  yum:
    name: docker
    state: latest
    update_cache: yes

- name: Make sure Docker is running
  service:
    name: docker
    state: running

- name: Grant access to ec2-user
  user:
    append: yes
    groups: docker
    name: ec2-user
