---
- hosts: all
  become: yes

  roles:
    - { role: base,   tags: ['base'  ] }
    - { role: docker, tags: ['docker'] }

- hosts: ghost
  become: yes

  vars:
    docker_gen_container_name: docker-gen-nginx-proxy

  roles:
    - { role: nginx_docker_gen, tags: ['nxinx_docker_gen'] }
    - { role: ghost,            tags: ['ghost'           ] }
    - { role: lets_encrypt,     tags: ['lets_encrypt'    ] }
