---
- name: Pull image for nginx-proxy
  docker_image:
    name: "{{ nginx_proxy_image }}"

- name: Deploy nginx-proxy
  docker_container:
    image: "{{ nginx_proxy_image }}"
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    name: "{{ nginx_proxy_container_name }}"
    networks:
      - name: "{{ docker_network_name }}"
    ports:
      - "80:80"
      - "443:443"
    restart_policy: always
    volumes:
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /opt/nginx/certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
