---
- name: Pull down Nginx Lets Encrypt image
  command: docker pull "{{ lets_encrypt_image }}"

- include: staging.yml
  when: lets_encrypt_environment == "staging"

- include: production.yml
  when: lets_encrypt_environment == "production"
