- name: Start Lets Encrypt container for STAGING environment
  docker:
    name: nginx-letsencrypt
    image: "{{ lets_encrypt_image }}"
    command: /bin/bash /app/start.sh --staging
    state: started
    restart_policy: always
    env:
      NGINX_DOCKER_GEN_CONTAINER: "{{ docker_gen_container_name }}"
    volumes:
      - /opt/nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from: "{{ docker_gen_container_name }}"
